<<<<<<< HEAD
# Generated by Django 5.2.14 on 2026-06-16 23:31
=======
# Generated by Django 5.2.12 on 2026-06-01 23:47
>>>>>>> e177c2d (bulk commit of unreviewed changes)

import tom_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_hermes', '0001_initial'),
    ]

    operations = [
<<<<<<< HEAD
        migrations.RemoveField(
            model_name='hermesprofile',
            name='_hermes_api_key_encrypted',
        ),
=======
>>>>>>> e177c2d (bulk commit of unreviewed changes)
        migrations.AddField(
            model_name='hermesprofile',
            name='hermes_api_key',
            field=tom_common.encryption.EncryptedModelField(blank=True, editable=True, null=True),
        ),
    ]
