# Generated by Django 5.2.14 on 2026-06-16 23:31

import tom_common.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_hermes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hermesprofile',
            name='_hermes_api_key_encrypted',
        ),
        migrations.AddField(
            model_name='hermesprofile',
            name='hermes_api_key',
            field=tom_common.encryption.EncryptedModelField(blank=True, editable=True, null=True),
        ),
    ]
